name: qr_attendance_project
description: "qr attendance project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # UI and Animations
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  lottie: ^3.3.0
  animated_splash_screen: ^1.3.0
  percent_indicator: ^4.2.4
  loading_animation_widget: ^1.3.0
  flutter_slider_drawer: ^3.0.2

  # QR
  mobile_scanner: ^7.0.1
  qr_flutter: ^4.1.0

  # Permissions
  permission_handler: ^12.0.0+1
  geolocator: ^14.0.0
  google_maps_flutter: ^2.12.2
  

  # State Management and Dependency Injection
  provider: ^6.1.2
  get_it: ^8.0.3

  # Data Management and Supporting Libraries
  shared_preferences: ^2.3.3
  intl: ^0.19.0
  equatable: ^2.0.7

  # Logging
  logger: ^2.5.0

  # Notification and Toast Messages
  flutter_toast_message_bar: ^0.0.8
  flutter_toastr: ^1.0.3
  fluttertoast: ^8.2.12

  # Multi-Language Support
  easy_localization: ^3.0.7+1

  # Firebase
  cloud_firestore: ^5.4.5
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.2
  google_sign_in: ^6.2.2
  firebase_storage: ^12.3.6
  hidden_drawer_menu: ^3.0.1
  

  #Exel file upload and select
  file_picker: ^10.0.0
  excel: ^2.1.0
  flutter_slidable: ^4.0.0
  glass_kit: ^4.0.1
  dropdown_button2: ^2.3.9
  shimmer: ^3.0.0
  flutter_spinbox: ^0.13.1
  circular_countdown_timer: ^0.2.4
  flutter_timer_countdown: ^1.0.7
  pdf: ^3.11.3
  share_plus: ^11.0.0
  printing: ^5.14.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/gifs/
    - assets/images/
    - assets/icons/
    - assets/langs/
    - assets/fonts/Roboto-Regular.ttf