// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfc2LW3a0x4HaLBPVVg2cCv1uduh9-vbs',
    appId: '1:647123881294:web:8f64fb0280fd9ca700e21f',
    messagingSenderId: '647123881294',
    projectId: 'bitirme-projesi-887a3',
    authDomain: 'bitirme-projesi-887a3.firebaseapp.com',
    storageBucket: 'bitirme-projesi-887a3.firebasestorage.app',
    measurementId: 'G-BYMS5WWNJC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc6Q0nLtj47Zmn23YZPjpjPDgkdv68sfg',
    appId: '1:647123881294:android:4354b0b856d561e100e21f',
    messagingSenderId: '647123881294',
    projectId: 'bitirme-projesi-887a3',
    storageBucket: 'bitirme-projesi-887a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8kfO3pmNGjorhhq0m_FMI4RwIEecNhsc',
    appId: '1:647123881294:ios:1490d788403d797400e21f',
    messagingSenderId: '647123881294',
    projectId: 'bitirme-projesi-887a3',
    storageBucket: 'bitirme-projesi-887a3.firebasestorage.app',
    iosBundleId: 'com.example.qrAttendanceProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8kfO3pmNGjorhhq0m_FMI4RwIEecNhsc',
    appId: '1:647123881294:ios:1490d788403d797400e21f',
    messagingSenderId: '647123881294',
    projectId: 'bitirme-projesi-887a3',
    storageBucket: 'bitirme-projesi-887a3.firebasestorage.app',
    iosBundleId: 'com.example.qrAttendanceProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfc2LW3a0x4HaLBPVVg2cCv1uduh9-vbs',
    appId: '1:647123881294:web:ba71978dd5705f5b00e21f',
    messagingSenderId: '647123881294',
    projectId: 'bitirme-projesi-887a3',
    authDomain: 'bitirme-projesi-887a3.firebaseapp.com',
    storageBucket: 'bitirme-projesi-887a3.firebasestorage.app',
    measurementId: 'G-K42PB2VTSZ',
  );

}